const SEASONAL_DATA = {
  1: {
    name: "1월",
    season: "겨울",
    color: "#5B9BD5",
    emoji: "❄️",
    vegetables: [
      { name: "시금치", emoji: "🥬", desc: "추위에 단맛이 올라옴" },
      { name: "배추", emoji: "🥬", desc: "겨울 배추는 속이 꽉 참" },
      { name: "무", emoji: "🫒", desc: "시원한 단맛, 소화에 좋음" },
      { name: "대파", emoji: "🌿", desc: "추울수록 달고 맛있음" },
      { name: "우엉", emoji: "🍂", desc: "식이섬유 풍부" },
    ],
    seafood: [
      { name: "굴", emoji: "🦪", desc: "바다의 우유, 1~2월이 제철" },
      { name: "대구", emoji: "🐟", desc: "겨울 생선의 대표주자" },
      { name: "홍합", emoji: "🦪", desc: "추운 겨울 영양 만점" },
      { name: "아귀", emoji: "🐡", desc: "겨울 보양식" },
    ],
    fruits: [
      { name: "귤", emoji: "🍊", desc: "비타민C 풍부한 겨울 과일" },
      { name: "한라봉", emoji: "🍊", desc: "제주 대표 겨울 과일" },
    ],
  },
  2: {
    name: "2월",
    season: "겨울/초봄",
    color: "#5B9BD5",
    emoji: "🌨️",
    vegetables: [
      { name: "냉이", emoji: "🌿", desc: "봄의 전령, 향긋한 향" },
      { name: "달래", emoji: "🌱", desc: "봄나물의 시작" },
      { name: "시금치", emoji: "🥬", desc: "겨울 시금치 마지막 시기" },
      { name: "무", emoji: "🫒", desc: "겨울 무 마무리" },
    ],
    seafood: [
      { name: "굴", emoji: "🦪", desc: "2월까지 최고 맛" },
      { name: "삼치", emoji: "🐟", desc: "지방 풍부한 겨울 생선" },
      { name: "가자미", emoji: "🐟", desc: "겨울~봄 제철" },
    ],
    fruits: [
      { name: "귤", emoji: "🍊", desc: "후기 귤로 더욱 달콤" },
      { name: "딸기", emoji: "🍓", desc: "온실 딸기 시즌 시작" },
    ],
  },
  3: {
    name: "3월",
    season: "봄",
    color: "#FF9CC0",
    emoji: "🌸",
    vegetables: [
      { name: "냉이", emoji: "🌿", desc: "봄나물의 여왕" },
      { name: "달래", emoji: "🌱", desc: "매콤달콤한 봄나물" },
      { name: "쑥", emoji: "🌿", desc: "봄 건강 나물" },
      { name: "두릅", emoji: "🌱", desc: "봄의 향기" },
      { name: "미나리", emoji: "🌿", desc: "향긋한 봄 채소" },
    ],
    seafood: [
      { name: "주꾸미", emoji: "🐙", desc: "봄 제철 낙지류" },
      { name: "도다리", emoji: "🐟", desc: "봄 도다리 쑥국" },
      { name: "바지락", emoji: "🦪", desc: "봄철 해감 쑥쑥" },
    ],
    fruits: [
      { name: "딸기", emoji: "🍓", desc: "봄 딸기 최성수기" },
    ],
  },
  4: {
    name: "4월",
    season: "봄",
    color: "#FF9CC0",
    emoji: "🌺",
    vegetables: [
      { name: "두릅", emoji: "🌱", desc: "4월 두릅이 가장 맛있음" },
      { name: "봄동", emoji: "🥬", desc: "봄 배추, 달고 부드러움" },
      { name: "취나물", emoji: "🌿", desc: "향긋한 봄나물" },
      { name: "고사리", emoji: "🌿", desc: "봄 고사리 채취 시기" },
      { name: "미나리", emoji: "🌿", desc: "봄 미나리 최성수기" },
    ],
    seafood: [
      { name: "주꾸미", emoji: "🐙", desc: "산란 전 알이 꽉 참" },
      { name: "멍게", emoji: "🦞", desc: "봄이 제철인 바다 향" },
      { name: "키조개", emoji: "🦪", desc: "관자 부드럽고 달콤" },
    ],
    fruits: [
      { name: "딸기", emoji: "🍓", desc: "딸기 시즌 후반" },
      { name: "참외", emoji: "🍈", desc: "초여름 참외 시작" },
    ],
  },
  5: {
    name: "5월",
    season: "봄/초여름",
    color: "#7BC67E",
    emoji: "🌻",
    vegetables: [
      { name: "아스파라거스", emoji: "🌿", desc: "봄철 최고 채소" },
      { name: "양파", emoji: "🧅", desc: "햇양파 출하 시작" },
      { name: "마늘", emoji: "🧄", desc: "풋마늘 수확 시기" },
      { name: "상추", emoji: "🥬", desc: "봄 상추 연하고 맛있음" },
      { name: "완두콩", emoji: "🫛", desc: "봄 완두콩 제철" },
    ],
    seafood: [
      { name: "참다랑어", emoji: "🐟", desc: "봄 참치 최고 시기" },
      { name: "문어", emoji: "🐙", desc: "5~6월 제철" },
      { name: "새우", emoji: "🦐", desc: "봄 대하 시작" },
    ],
    fruits: [
      { name: "참외", emoji: "🍈", desc: "여름 참외 시즌" },
      { name: "앵두", emoji: "🍒", desc: "초여름 앵두" },
    ],
  },
  6: {
    name: "6월",
    season: "여름",
    color: "#F9A825",
    emoji: "☀️",
    vegetables: [
      { name: "오이", emoji: "🥒", desc: "여름 수분 보충" },
      { name: "가지", emoji: "🍆", desc: "여름 채소의 대표" },
      { name: "애호박", emoji: "🥒", desc: "부드럽고 달콤" },
      { name: "고추", emoji: "🌶️", desc: "풋고추 수확 시기" },
      { name: "깻잎", emoji: "🌿", desc: "향긋한 여름 쌈채소" },
    ],
    seafood: [
      { name: "전복", emoji: "🦪", desc: "여름 전복 최고 맛" },
      { name: "민어", emoji: "🐟", desc: "여름 보양 생선" },
      { name: "오징어", emoji: "🦑", desc: "여름 오징어 시즌" },
    ],
    fruits: [
      { name: "수박", emoji: "🍉", desc: "여름의 왕" },
      { name: "복숭아", emoji: "🍑", desc: "여름 복숭아 시작" },
      { name: "토마토", emoji: "🍅", desc: "여름 토마토 최고 맛" },
    ],
  },
  7: {
    name: "7월",
    season: "여름",
    color: "#F9A825",
    emoji: "🌊",
    vegetables: [
      { name: "옥수수", emoji: "🌽", desc: "여름 옥수수 최성수기" },
      { name: "토마토", emoji: "🍅", desc: "방울토마토 풍성" },
      { name: "가지", emoji: "🍆", desc: "여름 가지 풍성" },
      { name: "여주", emoji: "🥒", desc: "여름 건강 채소" },
      { name: "오이", emoji: "🥒", desc: "시원한 여름 오이" },
    ],
    seafood: [
      { name: "장어", emoji: "🐍", desc: "복날 보양식 장어" },
      { name: "갈치", emoji: "🐟", desc: "제주 갈치 시즌" },
      { name: "낙지", emoji: "🐙", desc: "여름 낙지볶음" },
    ],
    fruits: [
      { name: "수박", emoji: "🍉", desc: "여름 수박 최성수기" },
      { name: "복숭아", emoji: "🍑", desc: "복숭아 최고 시기" },
      { name: "포도", emoji: "🍇", desc: "초복 포도 시작" },
    ],
  },
  8: {
    name: "8월",
    season: "여름",
    color: "#F9A825",
    emoji: "🌞",
    vegetables: [
      { name: "옥수수", emoji: "🌽", desc: "8월 찰옥수수 달콤" },
      { name: "풋콩", emoji: "🫛", desc: "여름 풋콩 수확" },
      { name: "고구마", emoji: "🍠", desc: "햇고구마 출하" },
      { name: "피망", emoji: "🫑", desc: "여름 피망 풍성" },
    ],
    seafood: [
      { name: "전복", emoji: "🦪", desc: "8월 전복 살 꽉 참" },
      { name: "꽃게", emoji: "🦀", desc: "여름 꽃게 알 가득" },
      { name: "참치", emoji: "🐟", desc: "여름 참치 회 시즌" },
    ],
    fruits: [
      { name: "복숭아", emoji: "🍑", desc: "천도복숭아 최성수기" },
      { name: "포도", emoji: "🍇", desc: "캠벨포도 출하" },
      { name: "무화과", emoji: "🍇", desc: "여름 무화과 시작" },
    ],
  },
  9: {
    name: "9월",
    season: "가을",
    color: "#E07B39",
    emoji: "🍂",
    vegetables: [
      { name: "고구마", emoji: "🍠", desc: "가을 고구마 달콤" },
      { name: "토란", emoji: "🥔", desc: "추석 필수 재료" },
      { name: "연근", emoji: "🌿", desc: "가을 연근 아삭" },
      { name: "버섯", emoji: "🍄", desc: "가을 송이버섯 시즌" },
      { name: "배추", emoji: "🥬", desc: "김장 배추 시작" },
    ],
    seafood: [
      { name: "꽃게", emoji: "🦀", desc: "가을 꽃게 최고 맛" },
      { name: "전어", emoji: "🐟", desc: "가을 전어 집나간 며느리도 돌아옴" },
      { name: "고등어", emoji: "🐟", desc: "가을 고등어 기름지고 맛있음" },
    ],
    fruits: [
      { name: "배", emoji: "🍐", desc: "가을 배 최고 시기" },
      { name: "사과", emoji: "🍎", desc: "홍옥 사과 출하" },
      { name: "포도", emoji: "🍇", desc: "머스캣 포도 최성수기" },
    ],
  },
  10: {
    name: "10월",
    season: "가을",
    color: "#E07B39",
    emoji: "🍁",
    vegetables: [
      { name: "무", emoji: "🫒", desc: "가을 무 단맛 최고" },
      { name: "배추", emoji: "🥬", desc: "김장철 배추" },
      { name: "버섯", emoji: "🍄", desc: "가을 능이버섯" },
      { name: "단호박", emoji: "🎃", desc: "가을 단호박 달콤" },
      { name: "밤", emoji: "🌰", desc: "가을 밤 수확" },
    ],
    seafood: [
      { name: "대하", emoji: "🦐", desc: "가을 대하 최성수기" },
      { name: "꽃게", emoji: "🦀", desc: "10월 꽃게 살 가득" },
      { name: "삼치", emoji: "🐟", desc: "가을 삼치 기름지고 고소" },
    ],
    fruits: [
      { name: "사과", emoji: "🍎", desc: "부사 사과 출하" },
      { name: "배", emoji: "🍐", desc: "신고 배 최성수기" },
      { name: "감", emoji: "🟠", desc: "가을 감 수확" },
    ],
  },
  11: {
    name: "11월",
    season: "가을/겨울",
    color: "#8D6E63",
    emoji: "🍃",
    vegetables: [
      { name: "배추", emoji: "🥬", desc: "김장 배추 최적기" },
      { name: "무", emoji: "🫒", desc: "김장 무" },
      { name: "대파", emoji: "🌿", desc: "겨울 대파 달콤" },
      { name: "시금치", emoji: "🥬", desc: "겨울 시금치 시작" },
    ],
    seafood: [
      { name: "굴", emoji: "🦪", desc: "11월 굴 시즌 시작" },
      { name: "도루묵", emoji: "🐟", desc: "겨울 도루묵 알 가득" },
      { name: "대구", emoji: "🐟", desc: "겨울 대구 시작" },
    ],
    fruits: [
      { name: "귤", emoji: "🍊", desc: "제주 귤 첫 출하" },
      { name: "사과", emoji: "🍎", desc: "후지 사과 최성수기" },
      { name: "감", emoji: "🟠", desc: "홍시, 곶감 시즌" },
    ],
  },
  12: {
    name: "12월",
    season: "겨울",
    color: "#5B9BD5",
    emoji: "⛄",
    vegetables: [
      { name: "시금치", emoji: "🥬", desc: "눈맞은 시금치 단맛" },
      { name: "배추", emoji: "🥬", desc: "겨울 배추 맛있는 시기" },
      { name: "무", emoji: "🫒", desc: "겨울 무 시원달콤" },
      { name: "우엉", emoji: "🍂", desc: "겨울 우엉 향 깊어짐" },
    ],
    seafood: [
      { name: "굴", emoji: "🦪", desc: "겨울 굴 최성수기" },
      { name: "대구", emoji: "🐟", desc: "대구탕 시즌" },
      { name: "방어", emoji: "🐟", desc: "12월 방어 기름지고 최고" },
      { name: "과메기", emoji: "🐟", desc: "포항 과메기 시즌" },
    ],
    fruits: [
      { name: "귤", emoji: "🍊", desc: "겨울 귤 최성수기" },
      { name: "한라봉", emoji: "🍊", desc: "제주 한라봉 출하" },
    ],
  },
};

const REGIONAL_DATA = {
  제주: {
    emoji: "🌺",
    color: "#FF6B9D",
    specialties: [
      { name: "한라봉", emoji: "🍊", season: "11~2월", desc: "제주 대표 감귤류" },
      { name: "흑돼지", emoji: "🐷", season: "연중", desc: "제주 흑돼지 오겹살" },
      { name: "갈치", emoji: "🐟", season: "7~10월", desc: "제주 은갈치" },
      { name: "전복", emoji: "🦪", season: "연중", desc: "제주 청정 바다 전복" },
      { name: "옥돔", emoji: "🐠", season: "10~3월", desc: "제주 특산 생선" },
      { name: "감귤", emoji: "🍊", season: "10~2월", desc: "제주 감귤 최고 품질" },
      { name: "오메기떡", emoji: "🍡", season: "연중", desc: "좁쌀로 만든 제주 향토 음식" },
    ],
  },
  경상도: {
    emoji: "⛰️",
    color: "#4CAF50",
    specialties: [
      { name: "대게", emoji: "🦀", season: "11~5월", desc: "영덕, 울진 대게" },
      { name: "과메기", emoji: "🐟", season: "11~2월", desc: "포항 구룡포 과메기" },
      { name: "멸치", emoji: "🐟", season: "3~6월", desc: "남해 죽방멸치" },
      { name: "마늘", emoji: "🧄", season: "5~6월", desc: "의성 마늘 전국 1위" },
      { name: "고령수박", emoji: "🍉", season: "5~8월", desc: "고령 수박 달콤" },
      { name: "사과", emoji: "🍎", season: "9~11월", desc: "청송 사과 유명" },
      { name: "자반고등어", emoji: "🐟", season: "연중", desc: "안동 간고등어" },
    ],
  },
  전라도: {
    emoji: "🌾",
    color: "#FFC107",
    specialties: [
      { name: "낙지", emoji: "🐙", season: "3~6월, 9~11월", desc: "무안, 신안 낙지" },
      { name: "꼬막", emoji: "🦪", season: "10~3월", desc: "벌교 꼬막" },
      { name: "홍어", emoji: "🐟", season: "연중", desc: "흑산도 홍어" },
      { name: "복숭아", emoji: "🍑", season: "7~8월", desc: "전라 복숭아 달콤" },
      { name: "고구마", emoji: "🍠", season: "9~11월", desc: "해남 고구마 전국 1위" },
      { name: "보성녹차", emoji: "🍵", season: "연중", desc: "보성 녹차 명품" },
      { name: "함평한우", emoji: "🥩", season: "연중", desc: "함평 한우 명품" },
    ],
  },
  충청도: {
    emoji: "🏔️",
    color: "#9C27B0",
    specialties: [
      { name: "인삼", emoji: "🌿", season: "9~10월", desc: "금산 인삼 세계 최고" },
      { name: "대추", emoji: "🫒", season: "9~10월", desc: "청양, 보은 대추" },
      { name: "딸기", emoji: "🍓", season: "12~5월", desc: "논산 딸기 전국 1위" },
      { name: "게장", emoji: "🦀", season: "3~5월, 9~10월", desc: "간장게장 밥도둑" },
      { name: "알밤", emoji: "🌰", season: "9~10월", desc: "공주 밤 전국 유명" },
      { name: "냉이", emoji: "🌿", season: "2~4월", desc: "봄나물 냉이" },
    ],
  },
  경기도: {
    emoji: "🏙️",
    color: "#2196F3",
    specialties: [
      { name: "이천쌀", emoji: "🌾", season: "9~10월", desc: "임금님 진상 이천쌀" },
      { name: "안성한우", emoji: "🥩", season: "연중", desc: "안성맞춤 한우" },
      { name: "파주장단콩", emoji: "🫘", season: "10~11월", desc: "두부, 된장 최고 재료" },
      { name: "포천이동갈비", emoji: "🍖", season: "연중", desc: "포천 이동 갈비 유명" },
      { name: "고양화훼", emoji: "🌸", season: "연중", desc: "화훼 수도권 최대 산지" },
    ],
  },
  강원도: {
    emoji: "🏔️",
    color: "#00BCD4",
    specialties: [
      { name: "황태", emoji: "🐟", season: "12~3월", desc: "대관령 황태 명품" },
      { name: "감자", emoji: "🥔", season: "6~8월", desc: "강원도 감자 최고" },
      { name: "옥수수", emoji: "🌽", season: "7~8월", desc: "강원 찰옥수수" },
      { name: "곤드레", emoji: "🌿", season: "4~6월", desc: "정선 곤드레밥" },
      { name: "더덕", emoji: "🌿", season: "9~11월", desc: "양구 더덕 유명" },
      { name: "오징어", emoji: "🦑", season: "6~11월", desc: "동해 오징어" },
      { name: "명태", emoji: "🐟", season: "11~2월", desc: "동해 명태 원산지" },
    ],
  },
};
